(function () {
    angular.module('htBillingApp', ['ngRoute']);
    angular.module('htBillingApp').config(function ($routeProvider) {
        $routeProvider.when('/', {
                templateUrl: 'templates/pages/login/login.html',
                controller: 'FormController',
                controllerAs: 'fc'
            })
            .when('/home', {
                templateUrl: 'templates/pages/home/home.html',
                controller: 'HomeController',
                controllerAs: 'homeCtrl'
            }).when('/operatorhome', {
                templateUrl: 'templates/pages/home/operatorhome.html',
                controller: 'OperatorHomeController',
                controllerAs: 'homeCtrl'
            }).when('/circlehome', {
                templateUrl: 'templates/pages/home/circlehome.html',
                controller: 'CircleHomeController',
                controllerAs: 'homeCtrl'
            }).when('/developerhome', {
                templateUrl: 'templates/pages/home/developerhome.html',
                controller: 'DeveloperController',
                controllerAs: 'developerCtrl'
            })
            .when('/enterreading', {
                templateUrl: 'templates/pages/meter/meterreading.html',
                controller: 'MeterReadingController',
                controllerAs: 'readingCtrl'
            }).when('/saved/:message', {
                templateUrl: 'templates/pages/meter/metersaved.html',
                controller: 'SaveController',
                controllerAs: 'saveCtrl'
            }).when('/viewmeterreadings', {
                templateUrl: 'templates/pages/meter/viewmeterreading2.html',
                controller: 'ViewMeterReadingsController',
                controllerAs: 'viewMeterReadingsCtrl'
            }).when('/addmeter', {
                templateUrl: 'templates/pages/meter/addmeter.html',
                controller: 'AddMeterController',
                controllerAs: 'addMeterCtrl'
            }).when('/addplant', {
                templateUrl: 'templates/pages/plant/addplant.html',
                controller: 'AddPlantController',
                controllerAs: 'addPlantCtrl'
            }).when('/adddeveloper', {
                templateUrl: 'templates/pages/developer/adddeveloper.html',
                controller: 'AddDeveloperController',
                controllerAs: 'addDeveloperCtrl'
            }).when('/addinvestor', {
                templateUrl: 'templates/pages/investor/addinvestor.html',
                controller: 'AddInvestorController',
                controllerAs: 'addInvestorCtrl'
            }).when('/addmachine', {
                templateUrl: 'templates/pages/machine/addmachine.html',
                controller: 'AddMachineController',
                controllerAs: 'addMachineCtrl'
            }).when('/viewdeveloperreading', {
                templateUrl: 'templates/pages/meter/viewdeveloperreading.html',
                controller: 'DeveloperViewMeterReadingsController',
                controllerAs: 'viewMeterReadingsCtrl'
            }).when('/splitreadings/:plantId/:meterNo', {
                templateUrl: 'templates/pages/meter/readingsbifircationpage.html',
                controller: 'BifircateReadingsController',
                controllerAs: 'viewMeterReadingsCtrl'
            }).when('/viewsplitedreadings/:plantId/:meterNo', {
                templateUrl: 'templates/pages/meter/viewbifircationpage.html',
                controller: 'ViewBifircateReadingsController',
                controllerAs: 'viewMeterReadingsCtrl'
            }).when('/viewbill/:billDetailsId', {
                templateUrl: 'templates/pages/meter/viewbill.html',
                controller: 'ViewBillController',
                controllerAs: 'viewBillCtrl'
            }).when('/viewcirclereadings', {
                templateUrl: 'templates/pages/meter/viewcirclereading.html',
                controller: 'ViewMeterReadingsController',
                controllerAs: 'viewMeterReadingsCtrl'
            }).when('/viewcircleconsumptions', {
                templateUrl: 'templates/pages/meter/circle_consumption_validation_page.html',
                controller: 'CircleConsumptionValidationController',
                controllerAs: 'circleConsumptionValidationController'
            }).when('/viewmeterdetails', {
                templateUrl: 'templates/pages/meter/viewmeterdetails.html',
                controller: 'ViewMeterDetailsController',
                controllerAs: 'viewMeterDetailsCtrl'
            }).when('/viewplantdetails', {
                templateUrl: 'templates/pages/plant/viewplantdetails.html',
                controller: 'ViewPlantDetailsController',
                controllerAs: 'viewPlantDetailsCtrl'
            }).when('/viewdeveloperdetails', {
                templateUrl: 'templates/pages/developer/viewdeveloperdetails.html',
                controller: 'ViewDeveloperDetailsController',
                controllerAs: 'viewDeveloperDetailsCtrl'
            }).when('/viewinvestordetails', {
                templateUrl: 'templates/pages/investor/viewinvestordetails.html',
                controller: 'ViewInvestorDetailsController',
                controllerAs: 'viewInvestorDetailsCtrl'
            }).when('/viewmachinedetails', {
                templateUrl: 'templates/pages/machine/viewmachinedetails.html',
                controller: 'ViewMachineDetailsController',
                controllerAs: 'viewMachineDetailsCtrl'
            });
    });
})();